parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello U-Centric Meter-2-Cash API
    version: 0.0.0
    # Enable the Varnish integration
    http_cache:
        invalidation:
            enabled: false
            #varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    collection:
        pagination:
            enabled: false