App\Entity\Product:
    attributes:
        id:
            groups:
                # -        
        name:
            groups:
                - product_read
                - product_write
        price:
            groups:
                - product_read
                - product_write
        upc:
            groups:
                - product_read
                - product_write
                
        status:
            groups:
                - product_read
                - product_write
                
        prodimg:
            groups:
                - product_read
                - product_write

        # BlameableTrait
        agent:
            groups:
                - product_read
        creator:
            groups:
                - product_read
                
        # TimestampableTrait
        dateCreated:
            groups:
                - product_read
        dateModified:
            groups:
                - product_read